In [147]:
import pandas as pd

In [148]:
df1 = pd.read_csv('archive (5)/arxiv_data.csv')
df2 = pd.read_csv('archive (5)/arxiv_data_210930-054931.csv')

In [149]:
df1

titles  \
0      Survey on Semantic Stereo Matching / Semantic ...   
1      FUTURE-AI: Guiding Principles and Consensus Re...   
2      Enforcing Mutual Consistency of Hard Regions f...   
3      Parameter Decoupling Strategy for Semi-supervi...   
4      Background-Foreground Segmentation for Interio...   
...                                                  ...   
51769  Hierarchically-coupled hidden Markov models fo...   
51770                         Blinking Molecule Tracking   
51771  Towards a Mathematical Foundation of Immunolog...   
51772  A Semi-Automatic Graph-Based Approach for Dete...   
51773  SparseCodePicking: feature extraction in mass ...   

                                               summaries  \
0      Stereo matching is one of the widely used tech...   
1      The recent advancements in artificial intellig...   
2      In this paper, we proposed a novel mutual cons...   
3      Consistency training has proven to be an advan...   
4      To ensure safety in automated driving, the cor...   
...                                                  ...   
51769  We address the problem of analyzing sets of no...   
51770  We discuss a method for tracking individual mo...   
51771  We attempt to set a mathematical foundation of...   
51772  Diffusion Tensor Imaging (DTI) allows estimati...   
51773  Mass spectrometry (MS) is an important techniq...   

                                                   terms  
0                                     ['cs.CV', 'cs.LG']  
1                            ['cs.CV', 'cs.AI', 'cs.LG']  
2                                     ['cs.CV', 'cs.AI']  
3                                              ['cs.CV']  
4                                     ['cs.CV', 'cs.LG']  
...                                                  ...  
51769          ['stat.ML', 'physics.bio-ph', 'q-bio.QM']  
51770                                 ['cs.CV', 'cs.DM']  
51771                   ['stat.ML', 'cs.LG', 'q-bio.GN']  
51772                                          ['cs.CV']  
51773  ['stat.ML', 'physics.med-ph', 'stat.AP', 'stat...  

[51774 rows x 3 columns]

In [150]:
df2

terms  \
0                                        ['cs.LG']   
1                               ['cs.LG', 'cs.AI']   
2                    ['cs.LG', 'cs.CR', 'stat.ML']   
3                               ['cs.LG', 'cs.CR']   
4                                        ['cs.LG']   
...                                            ...   
56176                           ['cs.CV', 'cs.IR']   
56177  ['cs.LG', 'cs.AI', 'cs.CL', 'I.2.6; I.2.7']   
56178                                    ['cs.LG']   
56179              ['stat.ML', 'cs.LG', 'math.OC']   
56180                ['cs.LG', 'cs.AI', 'stat.ML']   

                                                  titles  \
0      Multi-Level Attention Pooling for Graph Neural...   
1      Decision Forests vs. Deep Networks: Conceptual...   
2      Power up! Robust Graph Convolutional Network v...   
3      Releasing Graph Neural Networks with Different...   
4      Recurrence-Aware Long-Term Cognitive Network f...   
...                                                  ...   
56176  Mining Spatio-temporal Data on Industrializati...   
56177  Wav2Letter: an End-to-End ConvNet-based Speech...   
56178  Deep Reinforcement Learning with Double Q-lear...   
56179                        Generalized Low Rank Models   
56180  Chi-square Tests Driven Method for Learning th...   

                                               abstracts  
0      Graph neural networks (GNNs) have been widely ...  
1      Deep networks and decision forests (such as ra...  
2      Graph convolutional networks (GCNs) are powerf...  
3      With the increasing popularity of Graph Neural...  
4      Machine learning solutions for pattern classif...  
...                                                  ...  
56176  Despite the growing availability of big data i...  
56177  This paper presents a simple end-to-end model ...  
56178  The popular Q-learning algorithm is known to o...  
56179  Principal components analysis (PCA) is a well-...  
56180  SDYNA is a general framework designed to addre...  

[56181 rows x 3 columns]

In [151]:
df2['Combined'] = df2['titles'].astype(str) + '|||||.....ab: ' + df2['abstracts'].astype(str)
df2

terms  \
0                                        ['cs.LG']   
1                               ['cs.LG', 'cs.AI']   
2                    ['cs.LG', 'cs.CR', 'stat.ML']   
3                               ['cs.LG', 'cs.CR']   
4                                        ['cs.LG']   
...                                            ...   
56176                           ['cs.CV', 'cs.IR']   
56177  ['cs.LG', 'cs.AI', 'cs.CL', 'I.2.6; I.2.7']   
56178                                    ['cs.LG']   
56179              ['stat.ML', 'cs.LG', 'math.OC']   
56180                ['cs.LG', 'cs.AI', 'stat.ML']   

                                                  titles  \
0      Multi-Level Attention Pooling for Graph Neural...   
1      Decision Forests vs. Deep Networks: Conceptual...   
2      Power up! Robust Graph Convolutional Network v...   
3      Releasing Graph Neural Networks with Different...   
4      Recurrence-Aware Long-Term Cognitive Network f...   
...                                                  ...   
56176  Mining Spatio-temporal Data on Industrializati...   
56177  Wav2Letter: an End-to-End ConvNet-based Speech...   
56178  Deep Reinforcement Learning with Double Q-lear...   
56179                        Generalized Low Rank Models   
56180  Chi-square Tests Driven Method for Learning th...   

                                               abstracts  \
0      Graph neural networks (GNNs) have been widely ...   
1      Deep networks and decision forests (such as ra...   
2      Graph convolutional networks (GCNs) are powerf...   
3      With the increasing popularity of Graph Neural...   
4      Machine learning solutions for pattern classif...   
...                                                  ...   
56176  Despite the growing availability of big data i...   
56177  This paper presents a simple end-to-end model ...   
56178  The popular Q-learning algorithm is known to o...   
56179  Principal components analysis (PCA) is a well-...   
56180  SDYNA is a general framework designed to addre...   

                                                Combined  
0      Multi-Level Attention Pooling for Graph Neural...  
1      Decision Forests vs. Deep Networks: Conceptual...  
2      Power up! Robust Graph Convolutional Network v...  
3      Releasing Graph Neural Networks with Different...  
4      Recurrence-Aware Long-Term Cognitive Network f...  
...                                                  ...  
56176  Mining Spatio-temporal Data on Industrializati...  
56177  Wav2Letter: an End-to-End ConvNet-based Speech...  
56178  Deep Reinforcement Learning with Double Q-lear...  
56179  Generalized Low Rank Models|||||.....ab: Princ...  
56180  Chi-square Tests Driven Method for Learning th...  

[56181 rows x 4 columns]

In [152]:
df3 = df2.drop(columns = ["terms","abstracts","titles"])
df3

Combined
0      Multi-Level Attention Pooling for Graph Neural...
1      Decision Forests vs. Deep Networks: Conceptual...
2      Power up! Robust Graph Convolutional Network v...
3      Releasing Graph Neural Networks with Different...
4      Recurrence-Aware Long-Term Cognitive Network f...
...                                                  ...
56176  Mining Spatio-temporal Data on Industrializati...
56177  Wav2Letter: an End-to-End ConvNet-based Speech...
56178  Deep Reinforcement Learning with Double Q-lear...
56179  Generalized Low Rank Models|||||.....ab: Princ...
56180  Chi-square Tests Driven Method for Learning th...

[56181 rows x 1 columns]

In [153]:
df3['Combined'].nunique()

41120

In [154]:
df3.drop_duplicates(inplace= True)
df3.reset_index(drop= True,inplace = True)
df3

Combined
0      Multi-Level Attention Pooling for Graph Neural...
1      Decision Forests vs. Deep Networks: Conceptual...
2      Power up! Robust Graph Convolutional Network v...
3      Releasing Graph Neural Networks with Different...
4      Recurrence-Aware Long-Term Cognitive Network f...
...                                                  ...
41115  An experimental study of graph-based semi-supe...
41116  Bayesian Differential Privacy through Posterio...
41117  Mining Spatio-temporal Data on Industrializati...
41118  Wav2Letter: an End-to-End ConvNet-based Speech...
41119  Generalized Low Rank Models|||||.....ab: Princ...

[41120 rows x 1 columns]

In [155]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()


tfidf_matrix = vectorizer.fit_transform(df2['titles'])

In [156]:
tfidf_matrix1 = vectorizer.fit_transform(df3['Combined'])

In [157]:
print(tfidf_matrix)

  (0, 9711)	0.5167419487941495
  (0, 11075)	0.2780482816652611
  (0, 18956)	0.14008843706931304
  (0, 14359)	0.24850469117018092
  (0, 18104)	0.3694024869901276
  (0, 11367)	0.1554634761537394
  (0, 11374)	0.16352884180168073
  (0, 7396)	0.3491022979804692
  (0, 6632)	0.09221572357192351
  (0, 13056)	0.3308388378192037
  (0, 1207)	0.19343024982533533
  (0, 9515)	0.2734907927056635
  (0, 11013)	0.18675069421839552
  (1, 15746)	0.34745167357072376
  (1, 14962)	0.24120789673592366
  (1, 15861)	0.25393960925665504
  (1, 1157)	0.24720740942278732
  (1, 4714)	0.343206375789626
  (1, 5575)	0.2645984013252402
  (1, 791)	0.10090893591271319
  (1, 15671)	0.343206375789626
  (1, 3202)	0.3607459616622506
  (1, 4133)	0.12064846945440444
  (1, 18696)	0.2993163893186078
  (1, 6661)	0.2864738028221272
  :	:
  (56177, 5615)	0.524754636713243
  (56177, 17429)	0.1595371310514644
  (56177, 751)	0.2053089472691146
  (56177, 16934)	0.2654962776772991
  (56178, 5074)	0.7217241083649074
  (56178, 14198)	0.358

In [158]:
from sklearn.metrics.pairwise import cosine_similarity

new_text = "Attention is not all you need"
new_text_vector = vectorizer.transform([new_text])

In [159]:
cosine_similarities = cosine_similarity(new_text_vector, tfidf_matrix1)

In [160]:
cosine_similarities

array([[0.03188407, 0.00386253, 0.00606241, ..., 0.0246056 , 0.0426449 ,
        0.01939232]])

In [161]:
cosine_similarities

array([[0.03188407, 0.00386253, 0.00606241, ..., 0.0246056 , 0.0426449 ,
        0.01939232]])

In [162]:
import copy
cosine_simil = copy.deepcopy(cosine_similarities)

In [163]:
import numpy as np
sorted1 = np.sort(cosine_similarities,axis=1)

In [164]:
sorted1

array([[0.        , 0.        , 0.        , ..., 0.2355061 , 0.23600192,
        0.33442275]])

In [165]:
first_five = sorted1[:, -5:]
print(first_five)

[[0.21636988 0.22603469 0.2355061  0.23600192 0.33442275]]


In [166]:
first_five.shape

(1, 5)

In [167]:
indexes_max = []
i = 0
while i<5:
    indexes_max.append(cosine_simil.argmax())
    cosine_simil = np.delete(cosine_simil, cosine_simil.argmax())
    i+=1

In [168]:
indexes_max

[29391, 22282, 13207, 21710, 23749]

In [169]:
most_similar_text_5 = []
for all1 in indexes_max:
    most_similar_text_5.append(df3.loc[all1, 'Combined'])

In [170]:
most_similar_index = cosine_similarities.argmax()


most_similar_text = df3.loc[most_similar_index, 'Combined']

In [171]:
most_similar_index

29391

In [172]:
most_similar_text

'One Point is All You Need: Directional Attention Point for Feature Learning|||||.....ab: We present a novel attention-based mechanism for learning enhanced point\nfeatures for tasks such as point cloud classification and segmentation. Our key\nmessage is that if the right attention point is selected, then "one point is\nall you need" -- not a sequence as in a recurrent model and not a pre-selected\nset as in all prior works. Also, where the attention point is should be\nlearned, from data and specific to the task at hand. Our mechanism is\ncharacterized by a new and simple convolution, which combines the feature at an\ninput point with the feature at its associated attention point. We call such a\npoint a directional attention point (DAP), since it is found by adding to the\noriginal point an offset vector that is learned by maximizing the task\nperformance in training. We show that our attention mechanism can be easily\nincorporated into state-of-the-art point cloud classification an

In [173]:
for item in most_similar_text_5:
    print(item,'\n!.........................\n')

One Point is All You Need: Directional Attention Point for Feature Learning|||||.....ab: We present a novel attention-based mechanism for learning enhanced point
features for tasks such as point cloud classification and segmentation. Our key
message is that if the right attention point is selected, then "one point is
all you need" -- not a sequence as in a recurrent model and not a pre-selected
set as in all prior works. Also, where the attention point is should be
learned, from data and specific to the task at hand. Our mechanism is
characterized by a new and simple convolution, which combines the feature at an
input point with the feature at its associated attention point. We call such a
point a directional attention point (DAP), since it is found by adding to the
original point an offset vector that is learned by maximizing the task
performance in training. We show that our attention mechanism can be easily
incorporated into state-of-the-art point cloud classification and segmentati