In [234]:
import pandas as pd

In [235]:
df1 = pd.read_csv('archive (5)/arxiv_data.csv')
df2 = pd.read_csv('archive (5)/arxiv_data_210930-054931.csv')

In [236]:
df1

titles  \
0      Survey on Semantic Stereo Matching / Semantic ...   
1      FUTURE-AI: Guiding Principles and Consensus Re...   
2      Enforcing Mutual Consistency of Hard Regions f...   
3      Parameter Decoupling Strategy for Semi-supervi...   
4      Background-Foreground Segmentation for Interio...   
...                                                  ...   
51769  Hierarchically-coupled hidden Markov models fo...   
51770                         Blinking Molecule Tracking   
51771  Towards a Mathematical Foundation of Immunolog...   
51772  A Semi-Automatic Graph-Based Approach for Dete...   
51773  SparseCodePicking: feature extraction in mass ...   

                                               summaries  \
0      Stereo matching is one of the widely used tech...   
1      The recent advancements in artificial intellig...   
2      In this paper, we proposed a novel mutual cons...   
3      Consistency training has proven to be an advan...   
4      To ensure safety in automated driving, the cor...   
...                                                  ...   
51769  We address the problem of analyzing sets of no...   
51770  We discuss a method for tracking individual mo...   
51771  We attempt to set a mathematical foundation of...   
51772  Diffusion Tensor Imaging (DTI) allows estimati...   
51773  Mass spectrometry (MS) is an important techniq...   

                                                   terms  
0                                     ['cs.CV', 'cs.LG']  
1                            ['cs.CV', 'cs.AI', 'cs.LG']  
2                                     ['cs.CV', 'cs.AI']  
3                                              ['cs.CV']  
4                                     ['cs.CV', 'cs.LG']  
...                                                  ...  
51769          ['stat.ML', 'physics.bio-ph', 'q-bio.QM']  
51770                                 ['cs.CV', 'cs.DM']  
51771                   ['stat.ML', 'cs.LG', 'q-bio.GN']  
51772                                          ['cs.CV']  
51773  ['stat.ML', 'physics.med-ph', 'stat.AP', 'stat...  

[51774 rows x 3 columns]

In [237]:
df2

terms  \
0                                        ['cs.LG']   
1                               ['cs.LG', 'cs.AI']   
2                    ['cs.LG', 'cs.CR', 'stat.ML']   
3                               ['cs.LG', 'cs.CR']   
4                                        ['cs.LG']   
...                                            ...   
56176                           ['cs.CV', 'cs.IR']   
56177  ['cs.LG', 'cs.AI', 'cs.CL', 'I.2.6; I.2.7']   
56178                                    ['cs.LG']   
56179              ['stat.ML', 'cs.LG', 'math.OC']   
56180                ['cs.LG', 'cs.AI', 'stat.ML']   

                                                  titles  \
0      Multi-Level Attention Pooling for Graph Neural...   
1      Decision Forests vs. Deep Networks: Conceptual...   
2      Power up! Robust Graph Convolutional Network v...   
3      Releasing Graph Neural Networks with Different...   
4      Recurrence-Aware Long-Term Cognitive Network f...   
...                                                  ...   
56176  Mining Spatio-temporal Data on Industrializati...   
56177  Wav2Letter: an End-to-End ConvNet-based Speech...   
56178  Deep Reinforcement Learning with Double Q-lear...   
56179                        Generalized Low Rank Models   
56180  Chi-square Tests Driven Method for Learning th...   

                                               abstracts  
0      Graph neural networks (GNNs) have been widely ...  
1      Deep networks and decision forests (such as ra...  
2      Graph convolutional networks (GCNs) are powerf...  
3      With the increasing popularity of Graph Neural...  
4      Machine learning solutions for pattern classif...  
...                                                  ...  
56176  Despite the growing availability of big data i...  
56177  This paper presents a simple end-to-end model ...  
56178  The popular Q-learning algorithm is known to o...  
56179  Principal components analysis (PCA) is a well-...  
56180  SDYNA is a general framework designed to addre...  

[56181 rows x 3 columns]

In [238]:
df2['Combined'] = df2['titles'].astype(str) + '|||||.....ab: ' + df2['abstracts'].astype(str)
df2

terms  \
0                                        ['cs.LG']   
1                               ['cs.LG', 'cs.AI']   
2                    ['cs.LG', 'cs.CR', 'stat.ML']   
3                               ['cs.LG', 'cs.CR']   
4                                        ['cs.LG']   
...                                            ...   
56176                           ['cs.CV', 'cs.IR']   
56177  ['cs.LG', 'cs.AI', 'cs.CL', 'I.2.6; I.2.7']   
56178                                    ['cs.LG']   
56179              ['stat.ML', 'cs.LG', 'math.OC']   
56180                ['cs.LG', 'cs.AI', 'stat.ML']   

                                                  titles  \
0      Multi-Level Attention Pooling for Graph Neural...   
1      Decision Forests vs. Deep Networks: Conceptual...   
2      Power up! Robust Graph Convolutional Network v...   
3      Releasing Graph Neural Networks with Different...   
4      Recurrence-Aware Long-Term Cognitive Network f...   
...                                                  ...   
56176  Mining Spatio-temporal Data on Industrializati...   
56177  Wav2Letter: an End-to-End ConvNet-based Speech...   
56178  Deep Reinforcement Learning with Double Q-lear...   
56179                        Generalized Low Rank Models   
56180  Chi-square Tests Driven Method for Learning th...   

                                               abstracts  \
0      Graph neural networks (GNNs) have been widely ...   
1      Deep networks and decision forests (such as ra...   
2      Graph convolutional networks (GCNs) are powerf...   
3      With the increasing popularity of Graph Neural...   
4      Machine learning solutions for pattern classif...   
...                                                  ...   
56176  Despite the growing availability of big data i...   
56177  This paper presents a simple end-to-end model ...   
56178  The popular Q-learning algorithm is known to o...   
56179  Principal components analysis (PCA) is a well-...   
56180  SDYNA is a general framework designed to addre...   

                                                Combined  
0      Multi-Level Attention Pooling for Graph Neural...  
1      Decision Forests vs. Deep Networks: Conceptual...  
2      Power up! Robust Graph Convolutional Network v...  
3      Releasing Graph Neural Networks with Different...  
4      Recurrence-Aware Long-Term Cognitive Network f...  
...                                                  ...  
56176  Mining Spatio-temporal Data on Industrializati...  
56177  Wav2Letter: an End-to-End ConvNet-based Speech...  
56178  Deep Reinforcement Learning with Double Q-lear...  
56179  Generalized Low Rank Models|||||.....ab: Princ...  
56180  Chi-square Tests Driven Method for Learning th...  

[56181 rows x 4 columns]

In [239]:
df3 = df2.drop(columns = ["terms","abstracts","titles"])
df3

Combined
0      Multi-Level Attention Pooling for Graph Neural...
1      Decision Forests vs. Deep Networks: Conceptual...
2      Power up! Robust Graph Convolutional Network v...
3      Releasing Graph Neural Networks with Different...
4      Recurrence-Aware Long-Term Cognitive Network f...
...                                                  ...
56176  Mining Spatio-temporal Data on Industrializati...
56177  Wav2Letter: an End-to-End ConvNet-based Speech...
56178  Deep Reinforcement Learning with Double Q-lear...
56179  Generalized Low Rank Models|||||.....ab: Princ...
56180  Chi-square Tests Driven Method for Learning th...

[56181 rows x 1 columns]

In [240]:
df3['Combined'].nunique()

41120

In [241]:
df3.drop_duplicates(inplace= True)
df3.reset_index(drop= True,inplace = True)
df3

Combined
0      Multi-Level Attention Pooling for Graph Neural...
1      Decision Forests vs. Deep Networks: Conceptual...
2      Power up! Robust Graph Convolutional Network v...
3      Releasing Graph Neural Networks with Different...
4      Recurrence-Aware Long-Term Cognitive Network f...
...                                                  ...
41115  An experimental study of graph-based semi-supe...
41116  Bayesian Differential Privacy through Posterio...
41117  Mining Spatio-temporal Data on Industrializati...
41118  Wav2Letter: an End-to-End ConvNet-based Speech...
41119  Generalized Low Rank Models|||||.....ab: Princ...

[41120 rows x 1 columns]

In [242]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()


tfidf_matrix = vectorizer.fit_transform(df2['titles'])

In [243]:
tfidf_matrix1 = vectorizer.fit_transform(df3['Combined'])

In [244]:
print(tfidf_matrix)

  (0, 9711)	0.5167419487941495
  (0, 11075)	0.2780482816652611
  (0, 18956)	0.14008843706931304
  (0, 14359)	0.24850469117018092
  (0, 18104)	0.3694024869901276
  (0, 11367)	0.1554634761537394
  (0, 11374)	0.16352884180168073
  (0, 7396)	0.3491022979804692
  (0, 6632)	0.09221572357192351
  (0, 13056)	0.3308388378192037
  (0, 1207)	0.19343024982533533
  (0, 9515)	0.2734907927056635
  (0, 11013)	0.18675069421839552
  (1, 15746)	0.34745167357072376
  (1, 14962)	0.24120789673592366
  (1, 15861)	0.25393960925665504
  (1, 1157)	0.24720740942278732
  (1, 4714)	0.343206375789626
  (1, 5575)	0.2645984013252402
  (1, 791)	0.10090893591271319
  (1, 15671)	0.343206375789626
  (1, 3202)	0.3607459616622506
  (1, 4133)	0.12064846945440444
  (1, 18696)	0.2993163893186078
  (1, 6661)	0.2864738028221272
  :	:
  (56177, 5615)	0.524754636713243
  (56177, 17429)	0.1595371310514644
  (56177, 751)	0.2053089472691146
  (56177, 16934)	0.2654962776772991
  (56178, 5074)	0.7217241083649074
  (56178, 14198)	0.358

In [245]:
from sklearn.metrics.pairwise import cosine_similarity

new_text = "Attention is not all you need"
new_text_vector = vectorizer.transform([new_text])

In [246]:
cosine_similarities = cosine_similarity(new_text_vector, tfidf_matrix1)

In [247]:
cosine_similarities

array([[0.03188407, 0.00386253, 0.00606241, ..., 0.0246056 , 0.0426449 ,
        0.01939232]])

In [248]:
cosine_similarities

array([[0.03188407, 0.00386253, 0.00606241, ..., 0.0246056 , 0.0426449 ,
        0.01939232]])

In [249]:
import copy
cosine_simil = copy.deepcopy(cosine_similarities)

In [250]:
import numpy as np
sorted1 = np.sort(cosine_similarities,axis=1)

In [251]:
sorted1

array([[0.        , 0.        , 0.        , ..., 0.2355061 , 0.23600192,
        0.33442275]])

In [252]:
first_five = sorted1[:, -5:]
print(first_five)

[[0.21636988 0.22603469 0.2355061  0.23600192 0.33442275]]


In [253]:
first_five.shape

(1, 5)

In [254]:
indexes_max = []
i = 0
while i<5:
    indexes_max.append(cosine_simil.argmax())
    cosine_simil = np.delete(cosine_simil, cosine_simil.argmax())
    i+=1

In [255]:
indexes_max

[29391, 22282, 13207, 21710, 23749]

In [256]:
most_similar_text_5 = []
for all1 in indexes_max:
    most_similar_text_5.append(df3.loc[all1, 'Combined'])

In [257]:
most_similar_index = cosine_similarities.argmax()


most_similar_text = df3.loc[most_similar_index, 'Combined']

In [258]:
most_similar_index

29391

In [259]:
most_similar_text

'One Point is All You Need: Directional Attention Point for Feature Learning|||||.....ab: We present a novel attention-based mechanism for learning enhanced point\nfeatures for tasks such as point cloud classification and segmentation. Our key\nmessage is that if the right attention point is selected, then "one point is\nall you need" -- not a sequence as in a recurrent model and not a pre-selected\nset as in all prior works. Also, where the attention point is should be\nlearned, from data and specific to the task at hand. Our mechanism is\ncharacterized by a new and simple convolution, which combines the feature at an\ninput point with the feature at its associated attention point. We call such a\npoint a directional attention point (DAP), since it is found by adding to the\noriginal point an offset vector that is learned by maximizing the task\nperformance in training. We show that our attention mechanism can be easily\nincorporated into state-of-the-art point cloud classification an

In [260]:
for item in most_similar_text_5:
    print(item,'\n!.........................\n')

One Point is All You Need: Directional Attention Point for Feature Learning|||||.....ab: We present a novel attention-based mechanism for learning enhanced point
features for tasks such as point cloud classification and segmentation. Our key
message is that if the right attention point is selected, then "one point is
all you need" -- not a sequence as in a recurrent model and not a pre-selected
set as in all prior works. Also, where the attention point is should be
learned, from data and specific to the task at hand. Our mechanism is
characterized by a new and simple convolution, which combines the feature at an
input point with the feature at its associated attention point. We call such a
point a directional attention point (DAP), since it is found by adding to the
original point an offset vector that is learned by maximizing the task
performance in training. We show that our attention mechanism can be easily
incorporated into state-of-the-art point cloud classification and segmentati

In [261]:
!pip3.10 install -U sentence-transformers

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

[notice] A new release of pip is available: 23.0.1 -> 23.1.2
[notice] To update, run: pip3.10 install --upgrade pip


In [262]:
df2.drop_duplicates(inplace= True)
df2.reset_index(drop= True,inplace = True)
df2

terms  \
0                                        ['cs.LG']   
1                               ['cs.LG', 'cs.AI']   
2                    ['cs.LG', 'cs.CR', 'stat.ML']   
3                               ['cs.LG', 'cs.CR']   
4                                        ['cs.LG']   
...                                            ...   
41122                                  ['stat.ML']   
41123                         ['stat.ML', 'cs.LG']   
41124                           ['cs.CV', 'cs.IR']   
41125  ['cs.LG', 'cs.AI', 'cs.CL', 'I.2.6; I.2.7']   
41126              ['stat.ML', 'cs.LG', 'math.OC']   

                                                  titles  \
0      Multi-Level Attention Pooling for Graph Neural...   
1      Decision Forests vs. Deep Networks: Conceptual...   
2      Power up! Robust Graph Convolutional Network v...   
3      Releasing Graph Neural Networks with Different...   
4      Recurrence-Aware Long-Term Cognitive Network f...   
...                                                  ...   
41122  An experimental study of graph-based semi-supe...   
41123  Bayesian Differential Privacy through Posterio...   
41124  Mining Spatio-temporal Data on Industrializati...   
41125  Wav2Letter: an End-to-End ConvNet-based Speech...   
41126                        Generalized Low Rank Models   

                                               abstracts  \
0      Graph neural networks (GNNs) have been widely ...   
1      Deep networks and decision forests (such as ra...   
2      Graph convolutional networks (GCNs) are powerf...   
3      With the increasing popularity of Graph Neural...   
4      Machine learning solutions for pattern classif...   
...                                                  ...   
41122  The volume of data generated by internet and s...   
41123  Differential privacy formalises privacy-preser...   
41124  Despite the growing availability of big data i...   
41125  This paper presents a simple end-to-end model ...   
41126  Principal components analysis (PCA) is a well-...   

                                                Combined  
0      Multi-Level Attention Pooling for Graph Neural...  
1      Decision Forests vs. Deep Networks: Conceptual...  
2      Power up! Robust Graph Convolutional Network v...  
3      Releasing Graph Neural Networks with Different...  
4      Recurrence-Aware Long-Term Cognitive Network f...  
...                                                  ...  
41122  An experimental study of graph-based semi-supe...  
41123  Bayesian Differential Privacy through Posterio...  
41124  Mining Spatio-temporal Data on Industrializati...  
41125  Wav2Letter: an End-to-End ConvNet-based Speech...  
41126  Generalized Low Rank Models|||||.....ab: Princ...  

[41127 rows x 4 columns]

In [263]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')
embeddings = model.encode(df2['titles'])
print(embeddings)

[[ 0.06643409 -0.04954604  0.06388084 ...  0.00106309 -0.12156386
  -0.06962776]
 [ 0.09212266 -0.07606941  0.0657287  ... -0.0856517  -0.09266537
   0.00725293]
 [-0.08162682  0.02428936  0.01888737 ...  0.00806165 -0.05129535
  -0.05874001]
 ...
 [ 0.01227981 -0.08568834 -0.02782776 ... -0.0525798  -0.1080669
   0.0784331 ]
 [-0.07258197 -0.12690918 -0.00535553 ...  0.03597708 -0.03986146
  -0.05971038]
 [ 0.00768864 -0.10124185  0.08909855 ... -0.08199873 -0.05649747
   0.09007052]]


In [264]:
new_text_encoded = model.encode(new_text)
new_text_encoded

array([ 8.41662884e-02, -2.36604456e-02, -1.51677094e-02, -3.00083701e-02,
        8.17951038e-02,  2.19807774e-02,  6.44388869e-02, -2.66084969e-02,
        2.89261360e-02, -2.99789980e-02, -1.69187430e-02, -3.14490162e-02,
       -5.66774122e-02, -3.12639680e-03, -1.35714039e-02,  1.83753204e-02,
        1.28123909e-01, -4.11191061e-02, -1.09221242e-01, -2.05069091e-02,
       -2.15863567e-02, -1.03924386e-02,  9.49370787e-02, -3.11528742e-02,
       -1.04102857e-01,  3.01336008e-03, -6.85186312e-02, -7.08399266e-02,
       -4.70404542e-04, -1.79661177e-02,  2.75995173e-02, -1.60619838e-03,
        5.53941801e-02,  8.45082998e-02, -7.78045282e-02,  1.04016036e-01,
       -8.23812038e-02,  2.83071194e-02, -1.05232755e-02, -7.15080351e-02,
       -3.83403003e-02,  1.79515325e-03, -2.85560824e-02,  6.20898381e-02,
        5.22895157e-02, -6.62407652e-02,  4.88974936e-02, -9.83717758e-03,
        1.88271292e-02, -1.33619159e-01, -1.19439334e-01, -1.13510534e-01,
       -2.29885299e-02,  

In [265]:
cosine_similarities_2 = cosine_similarity([new_text_encoded], embeddings)
cosine_similarities_2

array([[ 0.3581707 ,  0.10183421,  0.08075173, ..., -0.03029852,
         0.14660074,  0.08696867]], dtype=float32)

In [266]:
torch.from_numpy(cosine_similarities_2)

tensor([[ 0.3582,  0.1018,  0.0808,  ..., -0.0303,  0.1466,  0.0870]])

In [267]:
import torch
top_similar_papers = torch.topk(torch.from_numpy(cosine_similarities_2),dim=1, k=5,sorted=True)
top_similar_papers

torch.return_types.topk(
values=tensor([[0.7756, 0.7261, 0.7174, 0.7138, 0.6914]]),
indices=tensor([[22910, 22285, 28559, 29962, 21475]]))

In [268]:
sentences = df2['titles']
for i in top_similar_papers.indices.tolist():
    print(sentences[i])

22910                 Attention that does not Explain Away
22285    Attention is Not All You Need: Pure Attention ...
28559             Why Attentions May Not Be Interpretable?
29962                              Attention as Activation
21475                                 Invertible Attention
Name: titles, dtype: object


In [270]:
import joblib
joblib.dump(model, 'transformer.joblib') 

['transformer.joblib']

In [271]:
joblib.dump(embeddings, 'embeddings.pkl')
joblib.dump(sentences, 'sentences.pkl')

['sentences.pkl']